spring:
  datasource:
    url: ENC(RSpSPnuhrslL92tC9h8ETU/I5h0IbcHWjw1Z3wDmO6cTRpPjtUOqVM514XeDMOsCwgPfm1hvTZpeW88aGyaLc2U43l3AeB5pb51KpMn7X1mo+pGZ6ibp8P2K+dEnw9LtEWuOTSXGqN0=)
    username: ENC(kvZLfziDLicXHT5X+g6/BE5/I1hYxkfM)
    password: ENC(DMYCBIVOHy8W5oZoYF0hmb2QvdnN0BWB)

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
