spring:
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  profiles:
    include:
      - oauth
      - aws
      - db
      - email

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  use-forward-headers: true