insert into positions(position) values('Electric Guitar');
insert into positions(position) values('Acoustic Guitar');
insert into positions(position) values('Drum');
insert into positions(position) values('Bass Guitar');
insert into positions(position) values('Keyboard');
insert into positions(position) values('Vocal');
insert into positions(position) values('Others');

insert into genres(genre) values('Rock');
insert into genres(genre) values('Metal');
insert into genres(genre) values('POP');
insert into genres(genre) values('J-POP');
insert into genres(genre) values('K-POP');
insert into genres(genre) values('Jazz');
insert into genres(genre) values('Blues');
insert into genres(genre) values('Punk');
insert into genres(genre) values('Hip-Hop');

insert into areas(city, district) values('서울시', '종로구');
insert into areas(city, district) values('서울시', '중구');
insert into areas(city, district) values('서울시', '용산구');
insert into areas(city, district) values('서울시', '성동구');
insert into areas(city, district) values('서울시', '광진구');
insert into areas(city, district) values('서울시', '동대문구');
insert into areas(city, district) values('서울시', '중랑구');
insert into areas(city, district) values('서울시', '성북구');
insert into areas(city, district) values('서울시', '강북구');
insert into areas(city, district) values('서울시', '도봉구');
insert into areas(city, district) values('서울시', '노원구');
insert into areas(city, district) values('서울시', '은평구');
insert into areas(city, district) values('서울시', '서대문구');
insert into areas(city, district) values('서울시', '마포구');
insert into areas(city, district) values('서울시', '양천구');
insert into areas(city, district) values('서울시', '강서구');
insert into areas(city, district) values('서울시', '구로구');
insert into areas(city, district) values('서울시', '금천구');
insert into areas(city, district) values('서울시', '영등포구');
insert into areas(city, district) values('서울시', '동작구');
insert into areas(city, district) values('서울시', '관악구');
insert into areas(city, district) values('서울시', '서초구');
insert into areas(city, district) values('서울시', '강남구');
insert into areas(city, district) values('서울시', '송파구');
insert into areas(city, district) values('서울시', '강동구');

insert into areas(city, district) values('인천시', '중구');
insert into areas(city, district) values('인천시', '동구');
insert into areas(city, district) values('인천시', '미추홀구');
insert into areas(city, district) values('인천시', '연수구');
insert into areas(city, district) values('인천시', '남동구');
insert into areas(city, district) values('인천시', '부평구');
insert into areas(city, district) values('인천시', '계양구');
insert into areas(city, district) values('인천시', '서구');
insert into areas(city, district) values('인천시', '강화군');
insert into areas(city, district) values('인천시', '옹진군');

insert into areas(city, district) values('경기도', '수원시 장안구');
insert into areas(city, district) values('경기도', '수원시 권선구');
insert into areas(city, district) values('경기도', '수원시 팔당구');
insert into areas(city, district) values('경기도', '수원시 영통구');
insert into areas(city, district) values('경기도', '성남시 수정구');
insert into areas(city, district) values('경기도', '성남시 중원구');
insert into areas(city, district) values('경기도', '성남시 분당구');
insert into areas(city, district) values('경기도', '부천시');
insert into areas(city, district) values('경기도', '안양시 만안구');
insert into areas(city, district) values('경기도', '안양시 동안구');
insert into areas(city, district) values('경기도', '안산시 상록구');
insert into areas(city, district) values('경기도', '안산시 단원구');
insert into areas(city, district) values('경기도', '용인시 처인구');
insert into areas(city, district) values('경기도', '용인시 기흥구');
insert into areas(city, district) values('경기도', '용인시 수지구');
insert into areas(city, district) values('경기도', '광명시');
insert into areas(city, district) values('경기도', '평택시');
insert into areas(city, district) values('경기도', '과천시');
insert into areas(city, district) values('경기도', '시흥시');
insert into areas(city, district) values('경기도', '군포시');
insert into areas(city, district) values('경기도', '의왕시');
insert into areas(city, district) values('경기도', '오산시');
insert into areas(city, district) values('경기도', '하남시');
insert into areas(city, district) values('경기도', '이천시');
insert into areas(city, district) values('경기도', '김포시');
insert into areas(city, district) values('경기도', '안성시');
insert into areas(city, district) values('경기도', '화성시');
insert into areas(city, district) values('경기도', '광주시');
insert into areas(city, district) values('경기도', '여주시');
insert into areas(city, district) values('경기도', '양평군');
insert into areas(city, district) values('경기도', '의정부시');
insert into areas(city, district) values('경기도', '고양시 덕양구');
insert into areas(city, district) values('경기도', '고양시 일산동구');
insert into areas(city, district) values('경기도', '고양시 일산서구');
insert into areas(city, district) values('경기도', '동두천시');
insert into areas(city, district) values('경기도', '구리시');
insert into areas(city, district) values('경기도', '남양주시');
insert into areas(city, district) values('경기도', '파주시');
insert into areas(city, district) values('경기도', '양주시');
insert into areas(city, district) values('경기도', '포천시');
insert into areas(city, district) values('경기도', '가평군');
insert into areas(city, district) values('경기도', '연천군');

insert into days(day) values('Mon');
insert into days(day) values('Tue');
insert into days(day) values('Wed');
insert into days(day) values('Thu');
insert into days(day) values('Fri');
insert into days(day) values('Sat');
insert into days(day) values('Sun');
