# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create application-db.yml
      run: |
          cd ./src/main/resources
          touch ./application-db.yml
          echo "${{ secrets.APPLICATION_DB }}" > ./application-db.yml
      shell: bash
      
    - name: Create application-aws.yml
      run: |
          cd ./src/main/resources
          touch ./application-aws.yml
          echo "${{ secrets.APPLICATION_AWS }}" > ./application-aws.yml
      shell: bash
  
    - name: Create application-oauth.yml
      run: |
          cd ./src/main/resources
          touch ./application-oauth.yml
          echo "${{ secrets.APPLICATION_OAUTH }}" > ./application-oauth.yml
      shell: bash
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Docker build & push to dev
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev ${{ secrets.DOCKER_REPO }}/bandwagon .
          docker push ${{ secrets.DOCKER_USERNAME }}/dotoriham-dev
